# Generated by Django 5.1.2 on 2024-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('titulo', models.CharField(blank=True, max_length=70)),
                ('paginas', models.PositiveIntegerField()),
                ('fecha_publicacion', models.DateField(null=True)),
                ('imagen', models.URLField(max_length=85, null=True)),
                ('desc_corta', models.CharField(max_length=2000)),
                ('estatus', models.CharField(choices=[('P', 'Publish'), ('M', 'Meap')], max_length=1)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
