# Generated by Django 5.1.2 on 2024-10-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AlterField(
            model_name='libro',
            name='desc_corta',
            field=models.CharField(default='Sin reseña', max_length=2000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
