# Generated by Django 5.1.2 on 2024-10-27 00:40

import libreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_libro_id_alter_libro_desc_corta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=70, validators=[libreria.models.validar_titulo]),
        ),
    ]
