# Generated by Django 5.1.2 on 2024-10-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='edicion_ant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.libro'),
        ),
    ]
