# Generated by Django 5.1.2 on 2024-10-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_librocronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libreria.editorial'),
            preserve_default=False,
        ),
    ]
